#!/bin/bash
if test "$#" -ne 1; then
    echo "Specify maximum number of bytes for shared memory"
    exit 0
fi
shmmax_size=$1
page_size=`getconf PAGESIZE`
shmmni=`cat /proc/sys/kernel/shmmni`
shmall_size=$(($shmmax_size*$shmmni/$page_size/16))
sudo bash -c "echo $shmmax_size > /proc/sys/kernel/shmmax"
sudo bash -c "echo $shmall_size > /proc/sys/kernel/shmall"

if grep -q "shmmax" "/etc/sysctl.conf"; then
  sudo sed -i "/kernel.shmmax/c\kernel.shmmax=$shmmax_size" /etc/sysctl.conf
else
  sudo bash -c "echo \"kernel.shmmax=$shmmax_size\" >> /etc/sysctl.conf"
fi

if grep -q "shmall" "/etc/sysctl.conf"; then
  sudo sed -i "/kernel.shmall/c\kernel.shmall=$shmall_size" /etc/sysctl.conf
else
  sudo bash -c "echo \"kernel.shmall=$shmall_size\" >> /etc/sysctl.conf"
fi
