#!/bin/bash
if test "$#" -ne 1; then
    echo "Specify maximum number of bytes for shared memory"
    exit 0
fi
shmmax_size=$1
page_size=`getconf PAGESIZE`
shmmni=`cat /proc/sys/kernel/shmmni`
shmall_size=$(($shmmax_size*$shmmni/$page_size/16))
sudo bash -c "echo \"kernel.shmmax=$shmmax_size\" >> /etc/sysctl.conf"
sudo bash -c "echo \"kernel.shmall=$shmall_size\" >> /etc/sysctl.conf"
