#!/bin/bash
if test "$#" -ne 1; then
    echo "Specify maximum number of bytes for shared memory"
    exit 0
fi
shmmax_size=$1
page_size=`getconf PAGESIZE`
shmmni=`cat /proc/sys/kernel/shmmni`
shmall_size=$(($shmmax_size*$shmmni/$page_size/16))
sudo bash -c "echo $shmmax_size > /proc/sys/kernel/shmmax"
sudo bash -c "echo $shmall_size > /proc/sys/kernel/shmall"
